language: ruby
rvm:
  - 2.2.2

postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - "psql -c 'create database calendar_on_rails_test;' -U postgres"
  - "rake db:migrate"
